name: metoffice_ec2
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - numcodecs
  - zarr
  - pytest
  - pandas
  - matplotlib
  - xarray
  - s3fs
  - boto3
  - cartopy
  - dask[array]
  - netCDF4
  - sentry-sdk
  - geojson
